src/main/java/org/oscarehr/caisi_integrator/site/ui/LoginJsfBean.java
package org.oscarehr.caisi_integrator.site.ui;

import java.util.GregorianCalendar;

import javax.faces.bean.ManagedBean;
import javax.persistence.Transient;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.oscarehr.caisi_integrator.dao.EventLogDao;
import org.oscarehr.caisi_integrator.dao.SiteUser;
import org.oscarehr.caisi_integrator.dao.SiteUserDao;
import org.oscarehr.caisi_integrator.site.utils.JsfUtils;
import org.oscarehr.caisi_integrator.site.utils.ReCaptchaUtils;
import org.oscarehr.caisi_integrator.site.utils.SiteSecurity;
import org.oscarehr.caisi_integrator.util.LoggedInInfoWebSite;
import org.oscarehr.caisi_integrator.util.MiscUtils;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class LoginJsfBean
{
	private static final Logger logger=MiscUtils.getLogger();
	
	@Transient
	private SiteUserDao siteUserDao=(SiteUserDao)SpringUtils.getBean("siteUserDao");

	@Transient
	private EventLogDao eventLogDao=(EventLogDao)SpringUtils.getBean("eventLogDao");
	
	private String username;
	private String password;
	
	public String getUsername()
	{
		return username;
	}

	public void setUsername(String username)
	{
		this.username = username.trim();
	}

	public String getPassword()
	{
		// no getting the password
		return("");
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public boolean isRecaptchaEnbled()
	{
		return(ReCaptchaUtils.enabled());
	}
	
	public String getRecaptchaPublicKey()
	{
		return(ReCaptchaUtils.PUBLIC_KEY);
	}
	
	public String login()
	{
		HttpServletRequest request=JsfUtils.getHttpServletRequest();
		HttpSession session=request.getSession();
		String requestingIp=request.getRemoteAddr();
		
		LoggedInInfoWebSite.setLoggedInInfoAtStartOfLoginAttempt();

		try
		{
			if (ReCaptchaUtils.enabled())
			{
				boolean validCaptcha=ReCaptchaUtils.validate(request);
				if (!validCaptcha)
				{
					JsfUtils.addErrorMessage("Invalid captcha");
					logger.warn("Invalid login attempt, bad captcha. ip="+requestingIp+", username="+username+", password="+password);
					
					eventLogDao.createLogicEventEntry("LOGIN"+MiscUtils.ID_SEPARATOR+"INVALID_CAPTCHA", "IP:"+requestingIp);
	
					return("login.jsf");
				}
			}
			
			SiteUser siteUser=siteUserDao.findByName(username);
			if (siteUser!=null)
			{
				if (siteUser.checkPassword(password) && !siteUser.isDisabled())
				{
					SiteSecurity.setLoggedInSiteUser(session, siteUser);
					LoggedInInfoWebSite.setAuthenticatedSiteUser(siteUser);
					
					eventLogDao.createLogicEventEntry("LOGIN"+MiscUtils.ID_SEPARATOR+"SUCCESS", "IP:"+requestingIp);

					siteUser.setLastLogin(new GregorianCalendar());
					siteUserDao.merge(siteUser);
					
					return("summary.jsf?"+JsfUtils.REDIRECT_QUERY_STRING);
				}
			}
		}
		catch (Exception e)
		{
			logger.warn("Unexpected error.", e);
		}
		
		JsfUtils.addErrorMessage("Invalid username or password.");
		logger.warn("Invalid login attempt, bad user/password. ip="+requestingIp+", username="+username+", password="+password);		
		eventLogDao.createLogicEventEntry("LOGIN"+MiscUtils.ID_SEPARATOR+"INVALID_USER_PASSWORD", "IP:"+requestingIp);

		SiteSecurity.removeLoggedInUser(session);

		return("login.jsf");
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/SimpleDateComponentBean.java
package org.oscarehr.caisi_integrator.site.ui;

import java.text.DateFormatSymbols;
import java.util.ArrayList;
import java.util.GregorianCalendar;

import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;

@ManagedBean
public class SimpleDateComponentBean
{
	public ArrayList<SelectItem> getListOfYears()
	{
		ArrayList<SelectItem> selectItems = new ArrayList<SelectItem>();

		GregorianCalendar cal = new GregorianCalendar();

		for (int i = cal.get(GregorianCalendar.YEAR); i >= 2008; i--)
		{
			String value = String.valueOf(i);
			selectItems.add(new SelectItem(value, value));
		}

		return(selectItems);
	}

	public ArrayList<SelectItem> getListOfMonths()
	{
		ArrayList<SelectItem> selectItems = new ArrayList<SelectItem>();

		DateFormatSymbols dateFormatSymbols = DateFormatSymbols.getInstance();
		String[] months = dateFormatSymbols.getShortMonths();

		for (int i = 1; i <= 12; i++)
		{
			String id = String.valueOf(i);
			String value = id + " (" + months[i - 1] + ')';
			selectItems.add(new SelectItem(id, value));
		}

		return(selectItems);
	}

	public ArrayList<SelectItem> getListOfDays()
	{
		ArrayList<SelectItem> selectItems = new ArrayList<SelectItem>();

		for (int i = 1; i <= 31; i++)
		{
			String value = String.valueOf(i);
			selectItems.add(new SelectItem(value, value));
		}

		return(selectItems);
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/admin/CreateUpdateFacilityJsfBean.java
package org.oscarehr.caisi_integrator.site.ui.admin;

import javax.faces.bean.ManagedBean;
import javax.persistence.Transient;

import org.apache.log4j.Logger;
import org.oscarehr.caisi_integrator.dao.Facility;
import org.oscarehr.caisi_integrator.dao.FacilityDao;
import org.oscarehr.caisi_integrator.site.utils.JsfUtils;
import org.oscarehr.caisi_integrator.util.MiscUtils;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class CreateUpdateFacilityJsfBean
{
	private static final Logger logger=MiscUtils.getLogger();

	@Transient
	private FacilityDao facilityDao = (FacilityDao)SpringUtils.getBean("facilityDao");

	private Facility facility = new Facility(); 
	private String password = null;

	public void setFacilityId(Integer facilityId)
	{
		if (facilityId==null) return;
		
		facility = facilityDao.find(facilityId);
	}

	public Integer getFacilityId()
	{
		return(facility.getId());
	}

	public Facility getFacility()
	{
		return facility;
	}

	public void setFacility(Facility facility)
	{
		this.facility = facility;
	}

	public boolean getIsNew()
	{
		return(facility.getId()==null);
	}
	
	public String getCreateUpdateTitle()
	{
		if (getIsNew()) return("Add new facility");
		else return("Update facility");
	}

	public String getPassword()
	{
		return password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public String save()
	{
		try
		{
			// save password
			if (password!=null && password.length()>0)
			{
				facility.setPassword(password);
			}
			
			// save the changes
			if (facility.getId()==null) facilityDao.persist(facility);
			else facilityDao.merge(facility);
		
			return("view_facilities.jsf?"+JsfUtils.REDIRECT_QUERY_STRING);
		}
		catch (Exception e)
		{
			logger.error("Unexpected error.", e);
			JsfUtils.addErrorMessage("Error creating Facility : "+e.getMessage());
			return(null);
		}
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/reports/HomelessPopulationReportConfigurationJsfBean.java
package org.oscarehr.caisi_integrator.site.ui.reports;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.GregorianCalendar;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.model.ListDataModel;
import javax.persistence.Transient;

import org.oscarehr.caisi_integrator.dao.CachedFacility;
import org.oscarehr.caisi_integrator.dao.CachedFacilityDao;
import org.oscarehr.caisi_integrator.dao.CachedProgram;
import org.oscarehr.caisi_integrator.dao.CachedProgramDao;
import org.oscarehr.caisi_integrator.dao.FacilityIdIntegerCompositePk;
import org.oscarehr.caisi_integrator.dao.HomelessPopulationReportDao;
import org.oscarehr.caisi_integrator.site.utils.JsfUtils;
import org.oscarehr.caisi_integrator.util.Named;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class HomelessPopulationReportConfigurationJsfBean implements Serializable
{
	@Transient
	private CachedFacilityDao cachedFacilityDao = (CachedFacilityDao)SpringUtils.getBean("cachedFacilityDao");
	
	@Transient
	private CachedProgramDao cachedProgramDao = (CachedProgramDao)SpringUtils.getBean("cachedProgramDao");

	@Transient
	private HomelessPopulationReportDao homelessPopulationReportDao = (HomelessPopulationReportDao)SpringUtils.getBean("homelessPopulationReportDao");

	private ArrayList<ProgramDisplayRow> resultRows = null;

	public static class ProgramDisplayRow implements Serializable, Named
	{
		private boolean checked=false;
		private FacilityIdIntegerCompositePk programId = null;
		private String facilityName = null;
		private String programName = null;
		private String programType = null;

		public ProgramDisplayRow(FacilityIdIntegerCompositePk programId, String facilityName, String programName, String programType)
		{
			this.programId = programId;
			this.facilityName = facilityName;
			this.programName = programName;
			this.programType = programType;
		}

		public boolean isChecked()
		{
			return checked;
		}

		public void setChecked(boolean checked)
		{
			this.checked = checked;
		}

		public FacilityIdIntegerCompositePk getProgramId()
		{
			return programId;
		}

		public void setProgramId(FacilityIdIntegerCompositePk programId)
		{
			this.programId = programId;
		}

		public String getFacilityName()
		{
			return facilityName;
		}

		public void setFacilityName(String facilityName)
		{
			this.facilityName = facilityName;
		}

		public String getProgramName()
		{
			return programName;
		}

		public void setProgramName(String programName)
		{
			this.programName = programName;
		}

		public String getProgramType()
		{
			return programType;
		}

		public void setProgramType(String programType)
		{
			this.programType = programType;
		}

		@Override
		public String getName()
		{
			return(facilityName +'.'+ programName +'.'+ programType);
		}

		
	}

	public ListDataModel<ProgramDisplayRow> getSelectedPrograms()
	{
		if (resultRows == null)
		{
			resultRows = new ArrayList<ProgramDisplayRow>();
			
			ArrayList<FacilityIdIntegerCompositePk> selectedProgramIds = homelessPopulationReportDao.getProgramsUsedReport(new GregorianCalendar());

			List<CachedProgram> cachedPrograms=cachedProgramDao.findAll();
			for (CachedProgram cachedProgram : cachedPrograms)
			{
				CachedFacility cachedFacility=cachedFacilityDao.find(cachedProgram.getId().getIntegratorFacilityId());				
				
				ProgramDisplayRow programDisplayRow=new ProgramDisplayRow(cachedProgram.getId(), cachedFacility.getName(), cachedProgram.getName(), cachedProgram.getType());

				programDisplayRow.setChecked(selectedProgramIds.contains(cachedProgram.getId()));
				
				resultRows.add(programDisplayRow);
			}
						
			Collections.sort(resultRows, Named.NAME_COMPARATOR);
		}

		ListDataModel<ProgramDisplayRow> results = new ListDataModel<ProgramDisplayRow>(resultRows);
		return(results);
	}

	public String save()
	{
		ArrayList<FacilityIdIntegerCompositePk> selectedProgramIds=new ArrayList<FacilityIdIntegerCompositePk>();
		
		for (ProgramDisplayRow row : resultRows)
		{
			if (row.isChecked())
			{
				selectedProgramIds.add(row.getProgramId());
			}
		}
		
		homelessPopulationReportDao.setProgramsToUseInReports(selectedProgramIds);
		
		JsfUtils.addInfoMessage("Changes Saved");
		
		return(null);
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/reports/HomelessPopulationReportResultsJsfBean.java
package org.oscarehr.caisi_integrator.site.ui.reports;

import java.io.Serializable;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.GregorianCalendar;

import javax.faces.bean.ManagedBean;
import javax.faces.model.ListDataModel;
import javax.persistence.Transient;

import org.oscarehr.caisi_integrator.dao.CachedFacility;
import org.oscarehr.caisi_integrator.dao.CachedFacilityDao;
import org.oscarehr.caisi_integrator.dao.CachedProgram;
import org.oscarehr.caisi_integrator.dao.CachedProgramDao;
import org.oscarehr.caisi_integrator.dao.FacilityIdIntegerCompositePk;
import org.oscarehr.caisi_integrator.dao.HomelessPopulationReport;
import org.oscarehr.caisi_integrator.dao.HomelessPopulationReportDao;
import org.oscarehr.caisi_integrator.util.Named;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class HomelessPopulationReportResultsJsfBean implements Serializable
{
	@Transient
	private CachedFacilityDao cachedFacilityDao = (CachedFacilityDao)SpringUtils.getBean("cachedFacilityDao");
	
	@Transient
	private CachedProgramDao cachedProgramDao = (CachedProgramDao)SpringUtils.getBean("cachedProgramDao");

	@Transient
	private HomelessPopulationReportDao homelessPopulationReportDao = (HomelessPopulationReportDao)SpringUtils.getBean("homelessPopulationReportDao");

	private Integer reportId = null;
	private HomelessPopulationReport homelessPopulationReport = null;
	private ArrayList<ProgramDisplayRow> programsUsedInReport=null;
	private NumberFormat percentInstance = NumberFormat.getPercentInstance();

	public HomelessPopulationReportResultsJsfBean()
	{
		percentInstance.setMinimumFractionDigits(0);
		percentInstance.setMaximumFractionDigits(2);
	}

	public void setReportId(Integer reportId)
	{
		this.reportId = reportId;
	}

	public Integer getReportId()
	{
		return(reportId);
	}

	public HomelessPopulationReport getHomelessPopulationReport()
	{
		if (homelessPopulationReport == null)
		{
			if (reportId == null) homelessPopulationReport = homelessPopulationReportDao.findFirstReportBeforeThisTime(new GregorianCalendar());
			else homelessPopulationReport = homelessPopulationReportDao.find(reportId);
		}

		return(homelessPopulationReport);
	}

	private String getRateString(int numerator, int denominator)
	{
		float f = (float)Math.max(numerator, 5) / Math.max(denominator, 5);

		StringBuilder sb = new StringBuilder();
		if (numerator < 5 || denominator < 5) sb.append('<');
		sb.append(percentInstance.format(f));

		return(sb.toString());
	}

	public String getMortalityRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getMortalityInPastYear(), report.getClientCountInPastYear()));
	}

	public String getCurrentHivRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentHiv(), report.getCurrentClientCount()));
	}

	public String getCurrentCancerRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentCancer(), report.getCurrentClientCount()));
	}

	public String getCurrentDiabetesRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentDiabetes(), report.getCurrentClientCount()));
	}

	public String getCurrentSeizureRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentSeizure(), report.getCurrentClientCount()));
	}

	public String getCurrentLiverDiseaseRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentLiverDisease(), report.getCurrentClientCount()));
	}

	public String getCurrentSchizophreniaRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentSchizophrenia(), report.getCurrentClientCount()));
	}

	public String getCurrentBipolarRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentBipolar(), report.getCurrentClientCount()));
	}

	public String getCurrentDepressionRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentDepression(), report.getCurrentClientCount()));
	}

	public String getCurrentCognitiveDisabilityRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentCognitiveDisability(), report.getCurrentClientCount()));
	}

	public String getCurrentPneumoniaRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentPneumonia(), report.getCurrentClientCount()));
	}

	public String getCurrentInfluenzaRate()
	{
		HomelessPopulationReport report = getHomelessPopulationReport();
		return(getRateString(report.getCurrentInfluenza(), report.getCurrentClientCount()));
	}

	public static class ProgramDisplayRow implements Serializable, Named
	{
		private String facilityName = null;
		private String programName = null;

		public String getFacilityName()
		{
			return facilityName;
		}

		public void setFacilityName(String facilityName)
		{
			this.facilityName = facilityName;
		}

		public String getProgramName()
		{
			return programName;
		}

		public void setProgramName(String programName)
		{
			this.programName = programName;
		}

		@Override
		public String getName()
		{
			return(facilityName+'.'+programName);
		}
	}
	
	public ListDataModel<ProgramDisplayRow> getProgramsUsed()
	{
		if (programsUsedInReport == null)
		{
			programsUsedInReport = new ArrayList<ProgramDisplayRow>();
			
			HomelessPopulationReport report = getHomelessPopulationReport();

			ArrayList<FacilityIdIntegerCompositePk> selectedProgramIds = homelessPopulationReportDao.getProgramsUsedReport(report.getReportTime());

			for (FacilityIdIntegerCompositePk programPk : selectedProgramIds)
			{
				CachedFacility cachedFacility=cachedFacilityDao.find(programPk.getIntegratorFacilityId());				
				CachedProgram cachedProgram=cachedProgramDao.find(programPk);

				ProgramDisplayRow programDisplayRow=new ProgramDisplayRow();
				programDisplayRow.facilityName=cachedFacility.getName();
				programDisplayRow.programName=cachedProgram.getName();
				
				programsUsedInReport.add(programDisplayRow);
			}
						
			Collections.sort(programsUsedInReport, Named.NAME_COMPARATOR);
		}

		ListDataModel<ProgramDisplayRow> results = new ListDataModel<ProgramDisplayRow>(programsUsedInReport);
		return(results);
	}
}

src/main/webapp/site/reports/homeless_population_report_configuration.xhtml
<ui:composition template="/resources/components/html_layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:caisi="http://caisi.ca/mytags">
	
	<ui:define name="body">		

		<h3>Homeless Population Report Configuration</h3> 
		
		<br />

		Checked programs will be included in future reports
		<h:form>
			<h:dataTable value="#{homelessPopulationReportConfigurationJsfBean.selectedPrograms}" var="row" styleClass="borderedCollapsedTable" headerClass="tableHeader showBorder" columnClasses="showBorder,showBorder,showBorder,showBorder" rowClasses="bgAlternatingGray,bgAlternatingGray1">
				<h:column>
					<h:selectBooleanCheckbox value="#{row.checked}" />
				</h:column>			
				<h:column>
					<f:facet name="header">Facility Name</f:facet>
					#{row.facilityName}
				</h:column>			
				<h:column>
					<f:facet name="header">Program Name</f:facet>
					#{row.programName}
				</h:column>			
				<h:column>
					<f:facet name="header">Program Type</f:facet>
					#{row.programType}
				</h:column>			
			</h:dataTable>
			
			<br />
			
			<div style="text-align:center">
				<h:commandButton value="Save" action="#{homelessPopulationReportConfigurationJsfBean.save}" />
				
				<h:button value="Cancel" outcome="index.jsf" />
			</div>
			
		</h:form>
		
	</ui:define>
	
</ui:composition>

src/main/webapp/site/reports/homeless_population_report_single_results.xhtml
<ui:composition template="/resources/components/html_layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:caisi="http://caisi.ca/mytags">
	
	<ui:define name="body">		
		<ui:include src="homeless_population_report_single_results_body.xhtml" />
	</ui:define>
	
</ui:composition>

src/main/webapp/site/reports/homeless_population_report_summary_of_results.xhtml
<ui:composition template="/resources/components/html_layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:caisi="http://caisi.ca/mytags">
	
	<ui:define name="body">		
		<ui:include src="homeless_population_report_summary_of_results_body.xhtml" />
	</ui:define>
	
</ui:composition>

src/main/webapp/site/reports/homeless_population_report_summary_of_results_body.xhtml
<html xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:caisi="http://caisi.ca/mytags">
	
	<h2>Homeless Population Report Results</h2> 

	<input type="button" onclick="document.location='homeless_population_report_single_results.jsf'" value="View Most Recent Report" />
	
	<br /><br />
	
	<hr />
	<h3>Previous Reports</h3>
	<h:form>
		<table>
			<tr>
				<td>Year</td>
				<td>Month</td>
				<td>Available Reports</td>
			</tr>
			<tr>
				<td>
					<h:selectOneListbox size="8" value="#{homelessPopulationReportSummaryJsfBean.selectedYear}" onchange="this.form.submit()">
						<f:selectItems value="#{homelessPopulationReportSummaryJsfBean.availableYears}"/>
					</h:selectOneListbox>					
				</td>
				<td>
					<h:selectOneListbox size="8" value="#{homelessPopulationReportSummaryJsfBean.selectedMonth}" onchange="this.form.submit()">
						<f:selectItems value="#{homelessPopulationReportSummaryJsfBean.availableMonths}"/>
					</h:selectOneListbox>					
				</td>
				<td>
					<h:selectOneListbox size="8" value="#{homelessPopulationReportSummaryJsfBean.selectedReportId}">
						<f:selectItems value="#{homelessPopulationReportSummaryJsfBean.availableReports}"/>
					</h:selectOneListbox>					
				</td>
			</tr>
		</table>
		<h:commandButton value="View Report" action="#{homelessPopulationReportSummaryJsfBean.viewReport}" />
	</h:form>
	
	<br /><br />

	<hr />
	<h3>Historical Daily Averages</h3>
	
	Number of clients in programs
	<caisi:renderAllYearsPopulationGraphs allYearsPopulationAverages="#{homelessPopulationReportSummaryJsfBean.allYearsPopulationAverages}" />

</html>

src/main/webapp/site/reports/index.xhtml
<ui:composition template="/resources/components/html_layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:caisi="http://caisi.ca/mytags">
	
	<ui:define name="body">
	
		<h3>Reports</h3>
	
		<ul>
			<li><a href="#{request.contextPath}/site/reports/issue_report_form.jsf">Issue Report</a></li>
			<li><a href="#{request.contextPath}/site/reports/homeless_population_report_summary_of_results.jsf">Homeless Population Reports</a></li>
			<li><a href="#{request.contextPath}/site/reports/homeless_population_report_configuration.jsf">Homeless Population Report Configuration</a></li>
		</ul>
	</ui:define>
	
</ui:composition>

src/main/webapp/site/reports/issue_report_export.jsp
<%@page import="org.apache.commons.lang.StringEscapeUtils"%>
<%@page import="java.io.PrintWriter"%>
<%@page import="java.util.ArrayList"%>
<%@page import="org.oscarehr.caisi_integrator.site.ui.reports.IssueReportJsfBean"%>

<%@page contentType="text/csv"%>
<%
	IssueReportJsfBean issueReportJsfBean=(IssueReportJsfBean)session.getAttribute("issueReportJsfBean");
	String filename=issueReportJsfBean.getReportDownloadFilename();
	response.setHeader("Content-Disposition", "attachment; filename="+filename);

	ArrayList<IssueReportJsfBean.IssueDisplayRow> rows=issueReportJsfBean.getReportResultsForDownload();
	
	PrintWriter writer=response.getWriter();

	for (IssueReportJsfBean.IssueDisplayRow row : rows)
	{
		String line=row.getOccuranceDate()+','+StringEscapeUtils.escapeCsv(row.getFacility())+','+StringEscapeUtils.escapeCsv(row.getIssueTypeCode())+','+StringEscapeUtils.escapeCsv(row.getIssueDescription());
		writer.println(line);
	}
	
	writer.flush();
%>

src/main/webapp/site/reports/view_all_logs.xhtml
<ui:composition template="/resources/components/html_layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:caisi="http://caisi.ca/mytags">
	
	<ui:define name="body">	
		
		
		
	</ui:define>
	
</ui:composition>