src/main/java/org/oscarehr/caisi_integrator/site/ui/SimpleDateComponentBean.java
package org.oscarehr.caisi_integrator.site.ui;

import java.text.DateFormatSymbols;
import java.util.ArrayList;
import java.util.GregorianCalendar;

import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;

@ManagedBean
public class SimpleDateComponentBean
{
	public ArrayList<SelectItem> getListOfYears()
	{
		ArrayList<SelectItem> selectItems = new ArrayList<SelectItem>();

		GregorianCalendar cal = new GregorianCalendar();

		for (int i = cal.get(GregorianCalendar.YEAR); i >= 2008; i--)
		{
			String value = String.valueOf(i);
			selectItems.add(new SelectItem(value, value));
		}

		return(selectItems);
	}

	public ArrayList<SelectItem> getListOfMonths()
	{
		ArrayList<SelectItem> selectItems = new ArrayList<SelectItem>();

		DateFormatSymbols dateFormatSymbols = DateFormatSymbols.getInstance();
		String[] months = dateFormatSymbols.getShortMonths();

		for (int i = 1; i <= 12; i++)
		{
			String id = String.valueOf(i);
			String value = id + " (" + months[i - 1] + ')';
			selectItems.add(new SelectItem(id, value));
		}

		return(selectItems);
	}

	public ArrayList<SelectItem> getListOfDays()
	{
		ArrayList<SelectItem> selectItems = new ArrayList<SelectItem>();

		for (int i = 1; i <= 31; i++)
		{
			String value = String.valueOf(i);
			selectItems.add(new SelectItem(value, value));
		}

		return(selectItems);
	}
}

src/main/webapp/resources/components/html_layout.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:caisi="http://caisi.ca/mytags">
	
	<h:head>
		<ui:insert name="customMeta"></ui:insert>
		<link rel="stylesheet" type="text/css" href="#{request.contextPath}/resources/css/default.css" title="default" />
		<title><ui:insert name="customTitle">Caisi Integrator</ui:insert></title>
		<ui:insert name="customStyle"></ui:insert>
	</h:head>
	<h:body>
		<table class="pageTable">
						
			<ui:remove>This is the top frame</ui:remove>
			<tr>
				<td class="pageFrameTopLeft"></td>
				<td class="pageFrameTopMiddle"></td>
				<td class="pageFrameTopRight"></td>
			</tr>

			<ui:remove>This is the top header</ui:remove>
			<ui:insert name="header">
				<tr>
					<td class="pageFrameLeftMiddle"></td>
					<td style="background-color: #008000; padding-bottom: 4px">
						<img src="#{request.contextPath}/resources/images/site_logo.png" alt="site_logo" />
					</td>
					<td class="pageFrameRightMiddle"></td>
				</tr>
			</ui:insert>

			<ui:remove>This is the top menu</ui:remove>
			<ui:insert name="menu">
				<tr>
					<td class="pageFrameLeftMiddle"></td>
					<td style="background-color:#008000">
						<ui:include src="/resources/components/menu.xhtml" />
					</td>
					<td class="pageFrameRightMiddle"></td>
				</tr>
			</ui:insert>

		
			<ui:remove>This is the main content</ui:remove>
			<tr>
				<td class="pageFrameLeftMiddle"></td>
				<td style="padding:16px;background-color:#ffffff">
					<div style="text-align:center">
						<h:messages infoClass="infoMessages" errorClass="errorMessages" />
					</div>
					
					<table style="margin-left:auto;margin-right:auto">
						<tr>
							<td>
								<ui:insert name="body">Missing Content</ui:insert>
							</td>
						</tr>
					</table>
				</td>
				<td class="pageFrameRightMiddle"></td>
			</tr>
				
			<ui:remove>This is the bottom frame</ui:remove>
			<tr>
				<td class="pageFrameBottomLeft"></td>
				<td class="pageFrameBottomMiddle"></td>
				<td class="pageFrameBottomRight"></td>
			</tr>

		</table>

		<div class="footer">
			Build date : #{caisi:buildDateTime()}
		</div>		
	
	</h:body>
</html>

src/main/webapp/resources/components/menu.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:caisi="http://caisi.ca/mytags">

	<table class="menu">
		<tr>
			<td>
				<a href="#{request.contextPath}/site/summary.jsf">Summary</a>
				|
				<a href="#{request.contextPath}/site/reports/index.jsf">Reports</a>
				|
				<a href="#{request.contextPath}/site/admin/index.jsf">Administration</a>				
			</td>
			<td style="text-align:right">
				<a href="#{request.contextPath}/site/logout.jsp">Logout</a>
			</td>
		</tr>
	</table>
	
</html>

src/main/webapp/resources/components/simple_date.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
    xmlns:composite="http://java.sun.com/jsf/composite">
    
    <!-- INTERFACE -->
    <composite:interface>
      <composite:attribute name="yearField" required="true" />
      <composite:attribute name="monthField" required="true" />
      <composite:attribute name="dayField" required="true" />
    </composite:interface> 
    
    <!-- IMPLEMENTATION -->
    <composite:implementation>
      			          
		<h:selectOneMenu value="#{cc.attrs.yearField}">
			<f:selectItems value="#{simpleDateComponentBean.listOfYears}" />
		</h:selectOneMenu>
		-
		<h:selectOneMenu value="#{cc.attrs.monthField}">
			<f:selectItems value="#{simpleDateComponentBean.listOfMonths}" />
		</h:selectOneMenu>
		-
		<h:selectOneMenu value="#{cc.attrs.dayField}">
			<f:selectItems value="#{simpleDateComponentBean.listOfDays}" />
		</h:selectOneMenu>
      			              
    </composite:implementation>
    
</html>