src/main/java/org/oscarehr/caisi_integrator/site/ui/LoginJsfBean.java
package org.oscarehr.caisi_integrator.site.ui;

import java.util.GregorianCalendar;

import javax.faces.bean.ManagedBean;
import javax.persistence.Transient;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.oscarehr.caisi_integrator.dao.EventLogDao;
import org.oscarehr.caisi_integrator.dao.SiteUser;
import org.oscarehr.caisi_integrator.dao.SiteUserDao;
import org.oscarehr.caisi_integrator.site.utils.JsfUtils;
import org.oscarehr.caisi_integrator.site.utils.ReCaptchaUtils;
import org.oscarehr.caisi_integrator.site.utils.SiteSecurity;
import org.oscarehr.caisi_integrator.util.LoggedInInfoWebSite;
import org.oscarehr.caisi_integrator.util.MiscUtils;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class LoginJsfBean
{
	private static final Logger logger=MiscUtils.getLogger();
	
	@Transient
	private SiteUserDao siteUserDao=(SiteUserDao)SpringUtils.getBean("siteUserDao");

	@Transient
	private EventLogDao eventLogDao=(EventLogDao)SpringUtils.getBean("eventLogDao");
	
	private String username;
	private String password;
	
	public String getUsername()
	{
		return username;
	}

	public void setUsername(String username)
	{
		this.username = username.trim();
	}

	public String getPassword()
	{
		// no getting the password
		return("");
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public boolean isRecaptchaEnbled()
	{
		return(ReCaptchaUtils.enabled());
	}
	
	public String getRecaptchaPublicKey()
	{
		return(ReCaptchaUtils.PUBLIC_KEY);
	}
	
	public String login()
	{
		HttpServletRequest request=JsfUtils.getHttpServletRequest();
		HttpSession session=request.getSession();
		String requestingIp=request.getRemoteAddr();
		
		LoggedInInfoWebSite.setLoggedInInfoAtStartOfLoginAttempt();

		try
		{
			if (ReCaptchaUtils.enabled())
			{
				boolean validCaptcha=ReCaptchaUtils.validate(request);
				if (!validCaptcha)
				{
					JsfUtils.addErrorMessage("Invalid captcha");
					logger.warn("Invalid login attempt, bad captcha. ip="+requestingIp+", username="+username+", password="+password);
					
					eventLogDao.createLogicEventEntry("LOGIN"+MiscUtils.ID_SEPARATOR+"INVALID_CAPTCHA", "IP:"+requestingIp);
	
					return("login.jsf");
				}
			}
			
			SiteUser siteUser=siteUserDao.findByName(username);
			if (siteUser!=null)
			{
				if (siteUser.checkPassword(password) && !siteUser.isDisabled())
				{
					SiteSecurity.setLoggedInSiteUser(session, siteUser);
					LoggedInInfoWebSite.setAuthenticatedSiteUser(siteUser);
					
					eventLogDao.createLogicEventEntry("LOGIN"+MiscUtils.ID_SEPARATOR+"SUCCESS", "IP:"+requestingIp);

					siteUser.setLastLogin(new GregorianCalendar());
					siteUserDao.merge(siteUser);
					
					return("summary.jsf?"+JsfUtils.REDIRECT_QUERY_STRING);
				}
			}
		}
		catch (Exception e)
		{
			logger.warn("Unexpected error.", e);
		}
		
		JsfUtils.addErrorMessage("Invalid username or password.");
		logger.warn("Invalid login attempt, bad user/password. ip="+requestingIp+", username="+username+", password="+password);		
		eventLogDao.createLogicEventEntry("LOGIN"+MiscUtils.ID_SEPARATOR+"INVALID_USER_PASSWORD", "IP:"+requestingIp);

		SiteSecurity.removeLoggedInUser(session);

		return("login.jsf");
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/SimpleDateComponentBean.java
package org.oscarehr.caisi_integrator.site.ui;

import java.text.DateFormatSymbols;
import java.util.ArrayList;
import java.util.GregorianCalendar;

import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;

@ManagedBean
public class SimpleDateComponentBean
{
	public ArrayList<SelectItem> getListOfYears()
	{
		ArrayList<SelectItem> selectItems = new ArrayList<SelectItem>();

		GregorianCalendar cal = new GregorianCalendar();

		for (int i = cal.get(GregorianCalendar.YEAR); i >= 2008; i--)
		{
			String value = String.valueOf(i);
			selectItems.add(new SelectItem(value, value));
		}

		return(selectItems);
	}

	public ArrayList<SelectItem> getListOfMonths()
	{
		ArrayList<SelectItem> selectItems = new ArrayList<SelectItem>();

		DateFormatSymbols dateFormatSymbols = DateFormatSymbols.getInstance();
		String[] months = dateFormatSymbols.getShortMonths();

		for (int i = 1; i <= 12; i++)
		{
			String id = String.valueOf(i);
			String value = id + " (" + months[i - 1] + ')';
			selectItems.add(new SelectItem(id, value));
		}

		return(selectItems);
	}

	public ArrayList<SelectItem> getListOfDays()
	{
		ArrayList<SelectItem> selectItems = new ArrayList<SelectItem>();

		for (int i = 1; i <= 31; i++)
		{
			String value = String.valueOf(i);
			selectItems.add(new SelectItem(value, value));
		}

		return(selectItems);
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/SummaryJsfBean.java
package org.oscarehr.caisi_integrator.site.ui;

import javax.faces.bean.ManagedBean;
import javax.persistence.Transient;

import org.oscarehr.caisi_integrator.dao.CachedDemographicDao;
import org.oscarehr.caisi_integrator.dao.CachedDemographicDrugDao;
import org.oscarehr.caisi_integrator.dao.CachedDemographicIssueDao;
import org.oscarehr.caisi_integrator.dao.CachedDemographicNoteDao;
import org.oscarehr.caisi_integrator.dao.CachedDemographicPreventionDao;
import org.oscarehr.caisi_integrator.dao.CachedFacilityDao;
import org.oscarehr.caisi_integrator.dao.CachedProgramDao;
import org.oscarehr.caisi_integrator.dao.CachedProviderDao;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class SummaryJsfBean
{
	@Transient
	private CachedFacilityDao cachedFacilityDao=(CachedFacilityDao)SpringUtils.getBean("cachedFacilityDao");

	@Transient
	private CachedProviderDao cachedProviderDao=(CachedProviderDao)SpringUtils.getBean("cachedProviderDao");
	
	@Transient
	private CachedDemographicDao cachedDemographicDao=(CachedDemographicDao)SpringUtils.getBean("cachedDemographicDao");
	
	@Transient
	private CachedProgramDao cachedProgramDao=(CachedProgramDao)SpringUtils.getBean("cachedProgramDao");
	
	@Transient
	private CachedDemographicNoteDao cachedDemographicNoteDao=(CachedDemographicNoteDao)SpringUtils.getBean("cachedDemographicNoteDao");
	
	@Transient
	private CachedDemographicIssueDao cachedDemographicIssueDao=(CachedDemographicIssueDao)SpringUtils.getBean("cachedDemographicIssueDao");
	
	@Transient
	private CachedDemographicPreventionDao cachedDemographicPreventionDao=(CachedDemographicPreventionDao)SpringUtils.getBean("cachedDemographicPreventionDao");

	@Transient
	private CachedDemographicDrugDao cachedDemographicDrugDao=(CachedDemographicDrugDao)SpringUtils.getBean("cachedDemographicDrugDao");
	
	public int getFacilityCount()
	{
		return(cachedFacilityDao.getCountAll());
	}

	public int getProviderCount()
	{
		return(cachedProviderDao.getCountAll());
	}

	public int getProgramCount()
	{
		return(cachedProgramDao.getCountAll());
	}

	public int getClientCount()
	{
		return(cachedDemographicDao.getCountAll());
	}

	public int getNoteCount()
	{
		return(cachedDemographicNoteDao.getCountAll());
	}

	public int getIssueCount()
	{
		return(cachedDemographicIssueDao.getCountAll());
	}

	public int getPreventionCount()
	{
		return(cachedDemographicPreventionDao.getCountAll());
	}

	public int getDrugCount()
	{
		return(cachedDemographicDrugDao.getCountAll());
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/admin/CreateUpdateFacilityJsfBean.java
package org.oscarehr.caisi_integrator.site.ui.admin;

import javax.faces.bean.ManagedBean;
import javax.persistence.Transient;

import org.apache.log4j.Logger;
import org.oscarehr.caisi_integrator.dao.Facility;
import org.oscarehr.caisi_integrator.dao.FacilityDao;
import org.oscarehr.caisi_integrator.site.utils.JsfUtils;
import org.oscarehr.caisi_integrator.util.MiscUtils;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class CreateUpdateFacilityJsfBean
{
	private static final Logger logger=MiscUtils.getLogger();

	@Transient
	private FacilityDao facilityDao = (FacilityDao)SpringUtils.getBean("facilityDao");

	private Facility facility = new Facility(); 
	private String password = null;

	public void setFacilityId(Integer facilityId)
	{
		if (facilityId==null) return;
		
		facility = facilityDao.find(facilityId);
	}

	public Integer getFacilityId()
	{
		return(facility.getId());
	}

	public Facility getFacility()
	{
		return facility;
	}

	public void setFacility(Facility facility)
	{
		this.facility = facility;
	}

	public boolean getIsNew()
	{
		return(facility.getId()==null);
	}
	
	public String getCreateUpdateTitle()
	{
		if (getIsNew()) return("Add new facility");
		else return("Update facility");
	}

	public String getPassword()
	{
		return password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public String save()
	{
		try
		{
			// save password
			if (password!=null && password.length()>0)
			{
				facility.setPassword(password);
			}
			
			// save the changes
			if (facility.getId()==null) facilityDao.persist(facility);
			else facilityDao.merge(facility);
		
			return("view_facilities.jsf?"+JsfUtils.REDIRECT_QUERY_STRING);
		}
		catch (Exception e)
		{
			logger.error("Unexpected error.", e);
			JsfUtils.addErrorMessage("Error creating Facility : "+e.getMessage());
			return(null);
		}
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/admin/CreateUpdateSiteUserJsfBean.java
package org.oscarehr.caisi_integrator.site.ui.admin;

import javax.faces.bean.ManagedBean;
import javax.persistence.Transient;

import org.apache.log4j.Logger;
import org.oscarehr.caisi_integrator.dao.SiteUser;
import org.oscarehr.caisi_integrator.dao.SiteUserDao;
import org.oscarehr.caisi_integrator.site.utils.JsfUtils;
import org.oscarehr.caisi_integrator.util.MiscUtils;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class CreateUpdateSiteUserJsfBean
{
	private static final Logger logger=MiscUtils.getLogger();

	@Transient
	private SiteUserDao siteUserDao = (SiteUserDao)SpringUtils.getBean("siteUserDao");

	private SiteUser siteUser = new SiteUser(); 
	private String password = null;

	public void setSiteUserId(Integer siteUserId)
	{
		if (siteUserId==null) return;
		
		siteUser = siteUserDao.find(siteUserId);
	}

	public Integer getSiteUserId()
	{
		return(siteUser.getId());
	}

	public SiteUser getSiteUser()
	{
		return siteUser;
	}

	public void setSiteUser(SiteUser siteUser)
	{
		this.siteUser = siteUser;
	}

	public boolean getIsNew()
	{
		return(siteUser.getId()==null);
	}
	
	public String getCreateUpdateTitle()
	{
		if (getIsNew()) return("Create new site user");
		else return("Update site user");
	}

	public String getPassword()
	{
		return password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public String save()
	{
		try
		{
			// save password
			if (password!=null && password.length()>0)
			{
				siteUser.setPassword(password);
			}
			
			// save the changes
			if (siteUser.getId()==null) siteUserDao.persist(siteUser);
			else siteUserDao.merge(siteUser);
		
			return("view_site_users.jsf?"+JsfUtils.REDIRECT_QUERY_STRING);
		}
		catch (Exception e)
		{
			logger.error("Unexpected error.", e);
			JsfUtils.addErrorMessage("Error creating SiteUser : "+e.getMessage());
			return(null);
		}
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/admin/DatabaseUpgradeJsfBean.java
package org.oscarehr.caisi_integrator.site.ui.admin;

import javax.faces.bean.ManagedBean;
import javax.persistence.Transient;

import org.apache.log4j.Logger;
import org.oscarehr.caisi_integrator.dao.SystemProperties;
import org.oscarehr.caisi_integrator.dao.SystemPropertiesDao;
import org.oscarehr.caisi_integrator.dao.schema.SchemaUpgradeManager;
import org.oscarehr.caisi_integrator.site.utils.JsfUtils;
import org.oscarehr.caisi_integrator.util.MiscUtils;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class DatabaseUpgradeJsfBean
{
	private static final Logger logger=MiscUtils.getLogger();

	@Transient
	private SystemPropertiesDao systemPropertiesDao = (SystemPropertiesDao)SpringUtils.getBean("systemPropertiesDao");

	public int getCodeDataVersion()
	{
		return(SystemProperties.CODE_SCHEMA_VERSION);
	}

	public int getDatabaseDataVersion()
	{
		SystemProperties systemProperties=null;
		
		try
		{
			systemProperties=systemPropertiesDao.find();
			return(systemProperties.getSchemaVersion());
		}
		catch (Exception e)
		{
			// no row, i.e. version 0
			return(0);
		}		
	}
	
	public boolean isDisableUpgradeButton()
	{
		return(getCodeDataVersion()==getDatabaseDataVersion());
	}
	
	public String upgrade()
	{
		if (getCodeDataVersion()==getDatabaseDataVersion()) return(null);
		
		try
		{
			SchemaUpgradeManager.upgradeDatabase();
			
			JsfUtils.addInfoMessage("Upgrade successful");
			JsfUtils.addErrorMessage("*** YOU MUST RESTART THE WEBAPP NOW ***");

			return(null);
		}
		catch (Exception e)
		{
			logger.error("Unexpected error.", e);
			JsfUtils.addErrorMessage("Error upgrading database : "+e.getMessage());
			return(null);
		}
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/admin/ViewFacilitiesJsfBean.java
package org.oscarehr.caisi_integrator.site.ui.admin;

import java.util.ArrayList;
import java.util.Collections;

import javax.faces.bean.ManagedBean;
import javax.faces.model.ListDataModel;
import javax.persistence.Transient;

import org.oscarehr.caisi_integrator.dao.Facility;
import org.oscarehr.caisi_integrator.dao.FacilityDao;
import org.oscarehr.caisi_integrator.util.Named;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class ViewFacilitiesJsfBean
{
	@Transient
	private FacilityDao facilityDao = (FacilityDao)SpringUtils.getBean("facilityDao");

	public ListDataModel<Facility> getAllFacilities()
	{
		// it's re-wrapped so I can sort it, JPA collections are immutable
		ArrayList<Facility> allfacilities = new ArrayList<Facility>(facilityDao.findAll());
		Collections.sort(allfacilities, Named.NAME_COMPARATOR);
		
		ListDataModel<Facility> results = new ListDataModel<Facility>(allfacilities);
		return(results);
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/admin/ViewSiteUsersJsfBean.java
package org.oscarehr.caisi_integrator.site.ui.admin;

import java.util.ArrayList;
import java.util.Collections;

import javax.faces.bean.ManagedBean;
import javax.faces.model.ListDataModel;
import javax.persistence.Transient;

import org.oscarehr.caisi_integrator.dao.SiteUser;
import org.oscarehr.caisi_integrator.dao.SiteUserDao;
import org.oscarehr.caisi_integrator.util.Named;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class ViewSiteUsersJsfBean
{
	@Transient
	private SiteUserDao siteUserDao = (SiteUserDao)SpringUtils.getBean("siteUserDao");

	public ListDataModel<SiteUser> getAllSiteUsers()
	{
		// it's re-wrapped so I can sort it, JPA collections are immutable
		ArrayList<SiteUser> allSiteUsers = new ArrayList<SiteUser>(siteUserDao.findAll());
		Collections.sort(allSiteUsers, Named.NAME_COMPARATOR);
		
		ListDataModel<SiteUser> results = new ListDataModel<SiteUser>(allSiteUsers);
		return(results);
	}
}

src/main/java/org/oscarehr/caisi_integrator/site/ui/reports/ViewAllLogsJsfBean.java
package org.oscarehr.caisi_integrator.site.ui.reports;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.model.ListDataModel;
import javax.persistence.Transient;

import org.oscarehr.caisi_integrator.dao.EventLog;
import org.oscarehr.caisi_integrator.dao.EventLogDao;
import org.oscarehr.caisi_integrator.util.SpringUtils;

@ManagedBean
public class ViewAllLogsJsfBean
{
	private static final int MAX_RESULTS = 100;

	@Transient
	private static EventLogDao eventLogDao = (EventLogDao) SpringUtils.getBean("eventLogDao");

	private int pageNum = 0;
	private int allLogsCount = -1;

	public void setPageNum(Integer pageNum)
	{
		if (pageNum != null)
		{
			if (pageNum < 0) this.pageNum = 0;
			else if (isPageNumTooBig(getLogCount())) this.pageNum = getMaxPages(getLogCount());
			else this.pageNum = pageNum;
		}
	}

	public int getPageNum()
	{
		return pageNum;
	}

	private boolean isPageNumTooBig(int totalLogs)
	{
		return(getPageNum() > getMaxPages(totalLogs));
	}

	private int getMaxPages(int totalLogs)
	{
		if (totalLogs == 0) return 0;
		else return (totalLogs - 1) / MAX_RESULTS;
	}

	public ListDataModel<EventLog> getEventLogs()
	{
		List<EventLog> list = eventLogDao.findAll(getPageNum() * MAX_RESULTS, MAX_RESULTS);
		return new ListDataModel<EventLog>(list);
	}

	public int getLogCount()
	{
		if (allLogsCount == -1)
		{
			allLogsCount = eventLogDao.getCountAll();
		}

		return(allLogsCount);
	}
}

src/main/webapp/site/index.jsp
<%response.sendRedirect("login.jsf");%>

src/main/webapp/site/login.xhtml
<ui:composition template="/resources/components/html_layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:caisi="http://caisi.ca/mytags">
	
	<ui:define name="customMeta">
		<ui:remove>prevent unrestoreable view error from session time out</ui:remove>
		<meta http-equiv="refresh" content="1800" />
	</ui:define>

	<ui:define name="menu">
		<ui:remove>no menu on this page</ui:remove>
	</ui:define>

	<ui:define name="body">
		<h:form>		
			<table class="roundedCollapsedTable">
				<tr>
					<td colspan="2" class="roundedTableHeader">Login</td>
				</tr>
				<tr>
					<td class="fieldLabel" style="padding-top:12px">User</td>
					<td style="padding-top:12px"><h:inputText value="#{loginJsfBean.username}" /></td>
				</tr>
				<tr>
					<td class="fieldLabel" style="padding-top:8px">Password</td>
					<td style="padding-top:12px"><h:inputSecret value="#{loginJsfBean.password}" /></td>
				</tr>
				<tr>
					<td colspan="2" style="padding-top:12px">
						<h:panelGroup rendered="#{loginJsfBean.recaptchaEnbled}">
							<script type="text/javascript" src="http://api.recaptcha.net/challenge?k=#{loginJsfBean.recaptchaPublicKey}">
							</script>
							<noscript>
								<iframe src="http://api.recaptcha.net/noscript?k=#{loginJsfBean.recaptchaPublicKey}" height="300" width="500" frameborder="0">
								</iframe>
								<br />
								<textarea name="recaptcha_challenge_field" rows="3" cols="40">
								</textarea>
								<input type="hidden" name="recaptcha_response_field" value="manual_challenge" />
						</noscript>
						</h:panelGroup>					
					</td>
				</tr>
				<tr>
					<td colspan="2" style="text-align:center;padding-top:12px;padding-bottom:8px"><h:commandButton value="Login" action="#{loginJsfBean.login}" /></td>
				</tr>
			</table>
		</h:form>
	</ui:define>
	
</ui:composition>

src/main/webapp/site/logout.jsp
<%
	request.getSession().invalidate();
	response.sendRedirect(request.getContextPath()+"/site");
%>

src/main/webapp/site/summary.xhtml
<ui:composition template="/resources/components/html_layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:caisi="http://caisi.ca/mytags">
	
	<ui:define name="body">
		<table class="roundedCollapsedTable">
			<tr>
				<td colspan="2" class="roundedTableHeader">Summary</td>
			</tr>
			<tr>
				<td class="fieldLabel">Total Facilities</td>
				<td>#{summaryJsfBean.facilityCount}</td>
			</tr>
			<tr>
				<td class="fieldLabel">Total Providers</td>
				<td>#{summaryJsfBean.providerCount}</td>
			</tr>
			<tr>
				<td class="fieldLabel">Total Programs</td>
				<td>#{summaryJsfBean.programCount}</td>
			</tr>
			<tr>
				<td class="fieldLabel">Total Clients</td>
				<td>#{summaryJsfBean.clientCount}</td>
			</tr>
			<tr>
				<td class="fieldLabel">Total Notes</td>
				<td>#{summaryJsfBean.noteCount}</td>
			</tr>
			<tr>
				<td class="fieldLabel">Total Issues</td>
				<td>#{summaryJsfBean.issueCount}</td>
			</tr>
			<tr>
				<td class="fieldLabel">Total Preventions</td>
				<td>#{summaryJsfBean.preventionCount}</td>
			</tr>
			<tr>
				<td class="fieldLabel">Total Drugs</td>
				<td>#{summaryJsfBean.drugCount}</td>
			</tr>
		</table>
	</ui:define>
	
</ui:composition>

src/main/webapp/site/upgrade.xhtml
<ui:composition template="/resources/components/html_layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:util="http://java.sun.com/jsf/composite/components"
	xmlns:caisi="http://caisi.ca/mytags">
	
	<ui:define name="menu">
		<ui:remove>no menu on this page</ui:remove>
	</ui:define>

	<ui:define name="body">	
	
		<h:form>
			<span style="font-weight:bold">Database Data Version</span> : #{databaseUpgradeJsfBean.databaseDataVersion}
			<br />	
			<span style="font-weight:bold">Code Data Version</span> : #{databaseUpgradeJsfBean.codeDataVersion}
			<br />
			<br />
			<h2 style="color:red">A reminder to make sure you have backed up your database first.</h2>
			<br />
			<h:commandButton value="Upgrade" disabled="#{databaseUpgradeJsfBean.disableUpgradeButton}" action="#{databaseUpgradeJsfBean.upgrade}" />
		</h:form>
		
	</ui:define>
	
</ui:composition>